# decoder params
code_type: Polar
code_len: 256
info_len: 128
clipping_val: 20
iteration_num: 5
early_stopping: True
design_SNR: 0.6

# data params
val_batch_size: 10000
val_SNR_start: 2.5
val_SNR_end: 2.5
val_num_SNR: 1
noise_seed: 345000
word_seed: 786000
test_errors: 500

# nn training
run_name: 'test'
load_weights: False
lr: 0.001
optimizer_type: 'ADAM'
criterion_type: 'BCE'
num_of_epochs: 100
validation_epochs: 5
train_minibatch_size: 100
train_SNR_start: 6
train_SNR_end: 8
train_num_SNR: 3
